### ISSUE TITLE
systest depends on libc 0.1, fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [alexcrichton/jemallocator#12]
cargo run --target $TARGET --manifest-path systest/Cargo.toml command is failing on ppc64le because systest depend on an older version of libc - 0.1, that is not supported on Power.

I tried to update the version of libc in systest/Cargo.toml to 0.2, however that in turn leads to the following failure:
root@ee2039143bce:~/jemallocator# cargo run --target $TARGET --manifest-path systest/Cargo.toml
   Compiling gcc v0.3.51
   Compiling unicode-xid v0.0.3
   Compiling libc v0.2.26
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling rustc-serialize v0.3.24
   Compiling log v0.3.8
   Compiling kernel32-sys v0.2.2
   Compiling jemalloc-sys v0.1.1 (file:///root/jemallocator/jemalloc-sys)
   Compiling term v0.2.14
   Compiling bitflags v0.3.3
   Compiling syntex_syntax v0.27.0
   Compiling ctest v0.1.4
   Compiling systest v0.1.0 (file:///root/jemallocator/systest)
error[E0432]: unresolved import `std::heap::System`
 --> systest/src/main.rs:7:5
  |
7 | use std::heap::System;
  |     ^^^^^^^^^^^^^^^^^ Could not find `heap` in `std`

error[E0554]: #[feature] may not be used on the stable release channel
 --> systest/src/main.rs:2:1
  |
2 | #![feature(global_allocator, allocator_api)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: The attribute `global_allocator` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> systest/src/main.rs:9:1
  |
9 | #[global_allocator]
  | ^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `systest`.

I will continue investigating this further.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this just isn't supported for now though, although updating the dependency on `syntex_syntax` in the `ctest` crate will likely fix this.

**Comment by seth-priya** [comment]
Thanks @alexcrichton, I will try this and get back.

**Comment by seth-priya** [comment]
Just a quick update here - ctest 0.1.4 seems to be completely supported on ppc64le. I could build and test it successfully. It did not give any issues in compiling the syntex_syntax crate either.

Logs, for reference
bash-4.2# cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.3.51
   Compiling winapi-build v0.1.1
   Compiling unicode-xid v0.0.3
   Compiling rustc-serialize v0.3.24
   Compiling log v0.3.8
   Compiling winapi v0.2.8
   Compiling libc v0.2.26
   Compiling bitflags v0.3.3
   Compiling kernel32-sys v0.2.2
   Compiling term v0.2.14
   Compiling syntex_syntax v0.27.0
   Compiling ctest v0.1.4 (file:///root/ctest-0.1.4)
    Finished dev [unoptimized + debuginfo] target(s) in 85.91 secs
bash-4.2# cargo test
   Compiling ctest v0.1.4 (file:///root/ctest-0.1.4)
    Finished dev [unoptimized + debuginfo] target(s) in 5.49 secs
     Running target/debug/deps/ctest-c14aa509210ac3fa

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests ctest

running 18 tests
test src/lib.rs - TestGenerator::generate (line 542) ... ok
test src/lib.rs - TestGenerator::define (line 229) ... ok
test src/lib.rs - TestGenerator::include (line 145) ... ok
test src/lib.rs - TestGenerator::skip_const (line 440) ... ok
test src/lib.rs - TestGenerator::field_name (line 302) ... ok
test src/lib.rs - TestGenerator::flag (line 167) ... ok
test src/lib.rs - TestGenerator::fn_cname (line 515) ... ok
test src/lib.rs - TestGenerator::skip_field_type (line 350) ... ok
test src/lib.rs - TestGenerator::out_dir (line 193) ... ok
test src/lib.rs - TestGenerator::header (line 123) ... ok
test src/lib.rs - TestGenerator::cfg (line 250) ... ok
test src/lib.rs - TestGenerator::skip_fn (line 399) ... ok
test src/lib.rs - TestGenerator::skip_struct (line 489) ... ok
test src/lib.rs - TestGenerator::skip_signededness (line 374) ... ok
test src/lib.rs - TestGenerator::skip_type (line 464) ... ok
test src/lib.rs - TestGenerator::skip_field (line 326) ... ok
test src/lib.rs - TestGenerator::target (line 211) ... ok
test src/lib.rs - TestGenerator::type_name (line 273) ... ok

test result: ok. 18 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by seth-priya** [comment]
I think the issue I am seeing is mostly due to the direct dependency that systest (i.e. jemallocator/systest) has on libc 0.1, which is not supported on ppc64le

From systest/Cargo.toml
[dependencies]
jemalloc-sys = { path = "../jemalloc-sys" }
libc = "0.1"

But I am running into other issues in attempting to upgrade this from here.

**Comment by seth-priya** [comment]
Hi @alexcrichton,
 I tracked the issue I was getting after updating the libc dependency in systest/Cargo.toml to gcc version. It seems there is an issue with gcc 5.x on both ppc64le and x86_64 (default on Ubuntu 16.04).

With gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) (on Ubuntu 14.04/ppc64le), I could successfully build and test jemallocator with just one change - updating libc from 0.1 to 0.2 in systest/Cargo.toml

Here are the logs
root@d48ab79080a3:~/jemallocator# # cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.3.51
   Compiling libc v0.2.26
   Compiling jemalloc-sys v0.1.1 (file:///root/test/jemallocator/jemalloc-sys)
   Compiling jemallocator v0.1.1 (file:///root/test/jemallocator)
    Finished dev [unoptimized + debuginfo] target(s) in 21.45 secs
root@d48ab79080a3:~/test/jemallocator# cargo test
   Compiling jemallocator v0.1.1 (file:///root/test/jemallocator)
    Finished dev [unoptimized + debuginfo] target(s) in 0.87 secs
     Running target/debug/deps/ffi-61bcae8ad393ef45

running 3 tests
test test_basic_alloc ... ok
test test_mallctl ... ok
test test_stats ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/malloctl-13085fdcdb43869b

running 2 tests
test smoke ... ok
test test_mallctl ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/smoke-c5602a364879c2fd

running 1 test
test smoke ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests jemallocator

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Please let me know if I should raise a PR or if you need any additional information/logs/testing to be done? Thanks!

Regards,
Priya

**Comment by alexcrichton** [comment]
PRs are certainly always welcome! Is this issue resolved for you though?

**Comment by seth-priya** [comment]
Hi @alexcrichton, yes, the ppc64le specific issue I was seeing is now resolved for me  - cargo build and cargo test work fine. Please do let me know if additional testing is required. Thanks!

**Comment by alexcrichton** [comment]
Looks good to me, thanks!
