### ISSUE TITLE
strdup is not handled properly

### ISSUE THREAD

**Issue by BusyJay** [alexcrichton/jemallocator#3]
Hi, when using this crate as custom memory allocator, the memory pointer returned by strdup can't be freed by libc::free. It seems jemalloc replace libc::free with its implementation, but strdup still uses default malloc. Am I missing any thing here?

**Comment by alexcrichton** [comment]
I'm not entirely sure :(. That may be a jemalloc issue, may be a linkage issue, or could also be something completely different ...
