### ISSUE TITLE
Shall we add a crate that sets up jemalloc as the global allocator?

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/jemallocator#32]
Every user needs to do the dance of:

```rust
#![feature(global_allocator)]

extern crate jemallocator;

use jemallocator::Jemalloc;

#[global_allocator]
static A: Jemalloc = Jemalloc;
```

Maybe it would be worth it to have a single crate, e.g., `global_allocator_jemalloc`, that does it, so that users only need to write:

```rust
extern crate global_allocator_jemalloc;
```

**Comment by alexcrichton** [comment]
I'd personally rather not, but I wouldn't object to someone else maintaining a crate.
