### ISSUE TITLE
Add feature to disable the zone allocator on Darwin

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/jemallocator#57]
As @sfackler mentioned we should add a feature to disable the zone allocator on Darwin.

---

cc @SimonSapin @glandium

**Comment by SimonSapin** [comment]
Or should it be disabled by default, with a cargo feature flag to enable it? (I have no opinion on this, but we do prefix public symbols by default.)

**Comment by sfackler** [comment]
I don't particularly want/need this feature - my question on #56 was more around if the feature's "goal" was to reroute malloc/free to jemalloc generally or to specifically not prefix the jemalloc public API.

**Comment by SimonSapin** [comment]
I think it’s fine to do nothing here until someone asks for it.
