### ISSUE TITLE
CI for Rust Beta and Stable

### ISSUE THREAD

**Issue by SimonSapin** [alexcrichton/jemallocator#62]
Since https://github.com/alexcrichton/jemallocator/pull/49 and Rust 1.28 (currently in Beta), this crate can run without unstable Rust features. We should add CI jobs for the Beta channel, and when 1.28 is released for the Stable channel.

**Comment by gnzlbg** [comment]
Great idea. I'll send a PR adding beta channel build bots for the tier 1 targets.

**Comment by gnzlbg** [comment]
Closed in #65 .
